import { ExcelDownloadType } from '../types/excelDownload';

export const excelDownload: ExcelDownloadType[] = [
  { label: 'pregunta_1,', value: 'pregunta_1' },
  { label: 'pregunta_2,', value: 'pregunta_2' },
  { label: 'pregunta_3,', value: 'pregunta_3' },
  { label: 'pregunta_3_otro,', value: 'pregunta_3_otro' },
  { label: 'pregunta_4,', value: 'pregunta_4' },
  { label: 'pregunta_5,', value: 'pregunta_5' },
  { label: 'pregunta_6_contacto,', value: 'pregunta_6_contacto' },
  { label: 'pregunta_6_numero,', value: 'pregunta_6_numero' },
  { label: 'pregunta_6_correo,', value: 'pregunta_6_correo' },
  { label: 'pregunta_6_contacto_2,', value: 'pregunta_6_contacto_2' },
  { label: 'pregunta_6_numero_2,', value: 'pregunta_6_numero_2' },
  { label: 'pregunta_6_correo_2,', value: 'pregunta_6_correo_2' },
  { label: 'pregunta_7,', value: 'pregunta_7' },
  { label: 'pregunta_8,', value: 'pregunta_8' },
  { label: 'pregunta_8_direccion,', value: 'pregunta_8_direccion' },
  { label: 'pregunta_9,', value: 'pregunta_9' },
  { label: 'pregunta_10,', value: 'pregunta_10' },
  { label: 'pregunta_10_otro,', value: 'pregunta_10_otro' },
  { label: 'pregunta_11,', value: 'pregunta_11' },
  { label: 'pregunta_11_otro,', value: 'pregunta_11_otro' },
  { label: 'pregunta_12,', value: 'pregunta_12' },
  { label: 'pregunta_12_otro,', value: 'pregunta_12_otro' },
  { label: 'pregunta_13,', value: 'pregunta_13' },
  { label: 'pregunta_13_otro,', value: 'pregunta_13_otro' },
  { label: 'pregunta_14,', value: 'pregunta_14' },
  {
    label: 'pregunta_14_asociados_cuantos,',
    value: 'pregunta_14_asociados_cuantos',
  },
  {
    label: 'pregunta_14_externos_cuantos,',
    value: 'pregunta_14_externos_cuantos',
  },
  { label: 'pregunta_15,', value: 'pregunta_15' },
  { label: 'pregunta_15_cuantos,', value: 'pregunta_15_cuantos' },
  { label: 'pregunta_16,', value: 'pregunta_16' },
  { label: 'pregunta_16_cuantos,', value: 'pregunta_16_cuantos' },
  { label: 'pregunta_17,', value: 'pregunta_17' },
  {
    label: 'pregunta_17_practicas_ordeno_cuantos,',
    value: 'pregunta_17_practicas_ordeno_cuantos',
  },
  {
    label: 'pregunta_17_practicas_ganaderas_cuantos,',
    value: 'pregunta_17_practicas_ganaderas_cuantos',
  },
  {
    label: 'pregunta_17_vacunacion_cuantos,',
    value: 'pregunta_17_vacunacion_cuantos',
  },
  {
    label: 'pregunta_17_brucela_tuberculosis_cuantos,',
    value: 'pregunta_17_brucela_tuberculosis_cuantos',
  },
  { label: 'pregunta_17_otro,', value: 'pregunta_17_otro' },
  { label: 'pregunta_17_otro_cuantos,', value: 'pregunta_17_otro_cuantos' },
  { label: 'pregunta_18,', value: 'pregunta_18' },
  { label: 'pregunta_19,', value: 'pregunta_19' },
  { label: 'pregunta_20,', value: 'pregunta_20' },
  { label: 'pregunta_21_n_grados,', value: 'pregunta_21_n_grados' },
  { label: 'pregunta_21_n_minutos,', value: 'pregunta_21_n_minutos' },
  { label: 'pregunta_21_n_segundos,', value: 'pregunta_21_n_segundos' },
  { label: 'pregunta_21_w_grados,', value: 'pregunta_21_w_grados' },
  { label: 'pregunta_21_w_minutos,', value: 'pregunta_21_w_minutos' },
  { label: 'pregunta_21_w_segundos,', value: 'pregunta_21_w_segundos' },
  { label: 'pregunta_22,', value: 'pregunta_22' },
  { label: 'pregunta_23,', value: 'pregunta_23' },
  { label: 'pregunta_23_otro,', value: 'pregunta_23_otro' },
  { label: 'pregunta_24_yogurt_diaria,', value: 'pregunta_24_yogurt_diaria' },
  {
    label: 'pregunta_24_yogurt_semanal,',
    value: 'pregunta_24_yogurt_semanal',
  },
  {
    label: 'pregunta_24_yogurt_mensual,',
    value: 'pregunta_24_yogurt_mensual',
  },
  {
    label: 'pregunta_24_yogurt_rendimiento,',
    value: 'pregunta_24_yogurt_rendimiento',
  },
  {
    label: 'pregunta_24_yogurt_vida_util,',
    value: 'pregunta_24_yogurt_vida_util',
  },
  { label: 'pregunta_24_kumis_diaria,', value: 'pregunta_24_kumis_diaria' },
  { label: 'pregunta_24_kumis_semanal,', value: 'pregunta_24_kumis_semanal' },
  { label: 'pregunta_24_kumis_mensual,', value: 'pregunta_24_kumis_mensual' },
  {
    label: 'pregunta_24_kumis_rendimiento,',
    value: 'pregunta_24_kumis_rendimiento',
  },
  {
    label: 'pregunta_24_kumis_vida_util,',
    value: 'pregunta_24_kumis_vida_util',
  },
  {
    label: 'pregunta_24_cuajada_diaria,',
    value: 'pregunta_24_cuajada_diaria',
  },
  {
    label: 'pregunta_24_cuajada_semanal,',
    value: 'pregunta_24_cuajada_semanal',
  },
  {
    label: 'pregunta_24_cuajada_mensual,',
    value: 'pregunta_24_cuajada_mensual',
  },
  {
    label: 'pregunta_24_cuajada_rendimiento,',
    value: 'pregunta_24_cuajada_rendimiento',
  },
  {
    label: 'pregunta_24_cuajada_vida_util,',
    value: 'pregunta_24_cuajada_vida_util',
  },
  {
    label: 'pregunta_24_queso_doble_crema_diaria,',
    value: 'pregunta_24_queso_doble_crema_diaria',
  },
  {
    label: 'pregunta_24_queso_doble_crema_semanal,',
    value: 'pregunta_24_queso_doble_crema_semanal',
  },
  {
    label: 'pregunta_24_queso_doble_crema_mensual,',
    value: 'pregunta_24_queso_doble_crema_mensual',
  },
  {
    label: 'pregunta_24_queso_doble_crema_rendimiento,',
    value: 'pregunta_24_queso_doble_crema_rendimiento',
  },
  {
    label: 'pregunta_24_queso_doble_crema_vida_util,',
    value: 'pregunta_24_queso_doble_crema_vida_util',
  },
  {
    label: 'pregunta_24_queso_campesino_diaria,',
    value: 'pregunta_24_queso_campesino_diaria',
  },
  {
    label: 'pregunta_24_queso_campesino_semanal,',
    value: 'pregunta_24_queso_campesino_semanal',
  },
  {
    label: 'pregunta_24_queso_campesino_mensual,',
    value: 'pregunta_24_queso_campesino_mensual',
  },
  {
    label: 'pregunta_24_queso_campesino_rendimiento,',
    value: 'pregunta_24_queso_campesino_rendimiento',
  },
  {
    label: 'pregunta_24_queso_campesino_vida_util,',
    value: 'pregunta_24_queso_campesino_vida_util',
  },
  { label: 'pregunta_24_leche_diaria,', value: 'pregunta_24_leche_diaria' },
  { label: 'pregunta_24_leche_semanal,', value: 'pregunta_24_leche_semanal' },
  { label: 'pregunta_24_leche_mensual,', value: 'pregunta_24_leche_mensual' },
  {
    label: 'pregunta_24_leche_rendimiento,',
    value: 'pregunta_24_leche_rendimiento',
  },
  {
    label: 'pregunta_24_leche_vida_util,',
    value: 'pregunta_24_leche_vida_util',
  },
  {
    label: 'pregunta_24_quesos_madurados_diaria,',
    value: 'pregunta_24_quesos_madurados_diaria',
  },
  {
    label: 'pregunta_24_quesos_madurados_semanal,',
    value: 'pregunta_24_quesos_madurados_semanal',
  },
  {
    label: 'pregunta_24_quesos_madurados_mensual,',
    value: 'pregunta_24_quesos_madurados_mensual',
  },
  {
    label: 'pregunta_24_quesos_madurados_rendimiento,',
    value: 'pregunta_24_quesos_madurados_rendimiento',
  },
  {
    label: 'pregunta_24_quesos_madurados_vida_util,',
    value: 'pregunta_24_quesos_madurados_vida_util',
  },
  {
    label: 'pregunta_24_requeson_diaria,',
    value: 'pregunta_24_requeson_diaria',
  },
  {
    label: 'pregunta_24_requeson_semanal,',
    value: 'pregunta_24_requeson_semanal',
  },
  {
    label: 'pregunta_24_requeson_mensual,',
    value: 'pregunta_24_requeson_mensual',
  },
  {
    label: 'pregunta_24_requeson_rendimiento,',
    value: 'pregunta_24_requeson_rendimiento',
  },
  {
    label: 'pregunta_24_requeson_vida_util,',
    value: 'pregunta_24_requeson_vida_util',
  },
  {
    label: 'pregunta_24_arequipe_diaria,',
    value: 'pregunta_24_arequipe_diaria',
  },
  {
    label: 'pregunta_24_arequipe_semanal,',
    value: 'pregunta_24_arequipe_semanal',
  },
  {
    label: 'pregunta_24_arequipe_mensual,',
    value: 'pregunta_24_arequipe_mensual',
  },
  {
    label: 'pregunta_24_arequipe_rendimiento,',
    value: 'pregunta_24_arequipe_rendimiento',
  },
  {
    label: 'pregunta_24_arequipe_vida_util,',
    value: 'pregunta_24_arequipe_vida_util',
  },
  {
    label: 'pregunta_24_leche_pasteurizada_diaria,',
    value: 'pregunta_24_leche_pasteurizada_diaria',
  },
  {
    label: 'pregunta_24_leche_pasteurizada_semanal,',
    value: 'pregunta_24_leche_pasteurizada_semanal',
  },
  {
    label: 'pregunta_24_leche_pasteurizada_mensual,',
    value: 'pregunta_24_leche_pasteurizada_mensual',
  },
  {
    label: 'pregunta_24_leche_pasteurizada_rendimiento,',
    value: 'pregunta_24_leche_pasteurizada_rendimiento',
  },
  {
    label: 'pregunta_24_leche_pasteurizada_vida_util,',
    value: 'pregunta_24_leche_pasteurizada_vida_util',
  },
  {
    label: 'pregunta_24_leche_UHT_diaria,',
    value: 'pregunta_24_leche_UHT_diaria',
  },
  {
    label: 'pregunta_24_leche_UHT_semanal,',
    value: 'pregunta_24_leche_UHT_semanal',
  },
  {
    label: 'pregunta_24_leche_UHT_mensual,',
    value: 'pregunta_24_leche_UHT_mensual',
  },
  {
    label: 'pregunta_24_leche_UHT_rendimiento,',
    value: 'pregunta_24_leche_UHT_rendimiento',
  },
  {
    label: 'pregunta_24_leche_UHT_vida_util,',
    value: 'pregunta_24_leche_UHT_vida_util',
  },
  {
    label: 'pregunta_24_postres_diaria,',
    value: 'pregunta_24_postres_diaria',
  },
  {
    label: 'pregunta_24_postres_semanal,',
    value: 'pregunta_24_postres_semanal',
  },
  {
    label: 'pregunta_24_postres_mensual,',
    value: 'pregunta_24_postres_mensual',
  },
  {
    label: 'pregunta_24_postres_rendimiento,',
    value: 'pregunta_24_postres_rendimiento',
  },
  {
    label: 'pregunta_24_postres_vida_util,',
    value: 'pregunta_24_postres_vida_util',
  },
  {
    label: 'pregunta_24_helados_diaria,',
    value: 'pregunta_24_helados_diaria',
  },
  {
    label: 'pregunta_24_helados_semanal,',
    value: 'pregunta_24_helados_semanal',
  },
  {
    label: 'pregunta_24_helados_mensual,',
    value: 'pregunta_24_helados_mensual',
  },
  {
    label: 'pregunta_24_helados_rendimiento,',
    value: 'pregunta_24_helados_rendimiento',
  },
  {
    label: 'pregunta_24_helados_vida_util,',
    value: 'pregunta_24_helados_vida_util',
  },
  {
    label: 'pregunta_24_crema_de_leche_diaria,',
    value: 'pregunta_24_crema_de_leche_diaria',
  },
  {
    label: 'pregunta_24_crema_de_leche_semanal,',
    value: 'pregunta_24_crema_de_leche_semanal',
  },
  {
    label: 'pregunta_24_crema_de_leche_mensual,',
    value: 'pregunta_24_crema_de_leche_mensual',
  },
  {
    label: 'pregunta_24_crema_de_leche_rendimiento,',
    value: 'pregunta_24_crema_de_leche_rendimiento',
  },
  {
    label: 'pregunta_24_crema_de_leche_vida_util,',
    value: 'pregunta_24_crema_de_leche_vida_util',
  },
  {
    label: 'pregunta_24_queso_mozzarella_diaria,',
    value: 'pregunta_24_queso_mozzarella_diaria',
  },
  {
    label: 'pregunta_24_queso_mozzarella_semanal,',
    value: 'pregunta_24_queso_mozzarella_semanal',
  },
  {
    label: 'pregunta_24_queso_mozzarella_mensual,',
    value: 'pregunta_24_queso_mozzarella_mensual',
  },
  {
    label: 'pregunta_24_queso_mozzarella_rendimiento,',
    value: 'pregunta_24_queso_mozzarella_rendimiento',
  },
  {
    label: 'pregunta_24_queso_mozzarella_vida_util,',
    value: 'pregunta_24_queso_mozzarella_vida_util',
  },
  { label: 'pregunta_25,', value: 'pregunta_25' },
  { label: 'pregunta_25_otro,', value: 'pregunta_25_otro' },
  { label: 'pregunta_26,', value: 'pregunta_26' },
  { label: 'pregunta_27,', value: 'pregunta_27' },
  { label: 'pregunta_28,', value: 'pregunta_28' },
  { label: 'pregunta_29,', value: 'pregunta_29' },
  { label: 'pregunta_30,', value: 'pregunta_30' },
  { label: 'pregunta_31,', value: 'pregunta_31' },
  { label: 'pregunta_32,', value: 'pregunta_32' },
  { label: 'pregunta_33,', value: 'pregunta_33' },
  { label: 'pregunta_33_otro,', value: 'pregunta_33_otro' },
  { label: 'pregunta_34,', value: 'pregunta_34' },
  { label: 'pregunta_34_otro,', value: 'pregunta_34_otro' },
  { label: 'pregunta_35,', value: 'pregunta_35' },
  { label: 'pregunta_35_otro,', value: 'pregunta_35_otro' },
  { label: 'pregunta_36,', value: 'pregunta_36' },
  { label: 'pregunta_36_cuales,', value: 'pregunta_36_cuales' },
  { label: 'pregunta_37,', value: 'pregunta_37' },
  { label: 'pregunta_37_calificacion,', value: 'pregunta_37_calificacion' },
  { label: 'pregunta_38,', value: 'pregunta_38' },
  { label: 'pregunta_39,', value: 'pregunta_39' },
  { label: 'pregunta_40,', value: 'pregunta_40' },
  { label: 'pregunta_40_cuales,', value: 'pregunta_40_cuales' },
  { label: 'pregunta_41,', value: 'pregunta_41' },
  { label: 'pregunta_41_cuales,', value: 'pregunta_41_cuales' },
  { label: 'pregunta_42,', value: 'pregunta_42' },
  { label: 'pregunta_42_como,', value: 'pregunta_42_como' },
  {
    label: 'pregunta_43_microbiologicas,',
    value: 'pregunta_43_microbiologicas',
  },
  {
    label: 'pregunta_43_microbiologicas_cuales,',
    value: 'pregunta_43_microbiologicas_cuales',
  },
  { label: 'pregunta_43_fisicoquimica,', value: 'pregunta_43_fisicoquimica' },
  {
    label: 'pregunta_43_fisicoquimica_cuales,',
    value: 'pregunta_43_fisicoquimica_cuales',
  },
  {
    label: 'pregunta_43_organolepticas,',
    value: 'pregunta_43_organolepticas',
  },
  {
    label: 'pregunta_43_organolepticas_cuales,',
    value: 'pregunta_43_organolepticas_cuales',
  },
  { label: 'pregunta_44,', value: 'pregunta_44' },
  { label: 'pregunta_44_como,', value: 'pregunta_44_como' },
  { label: 'pregunta_45,', value: 'pregunta_45' },
  { label: 'pregunta_45_otro,', value: 'pregunta_45_otro' },
  { label: 'pregunta_46,', value: 'pregunta_46' },
  { label: 'pregunta_46_cuales,', value: 'pregunta_46_cuales' },
  { label: 'pregunta_47,', value: 'pregunta_47' },
  { label: 'pregunta_47_cual,', value: 'pregunta_47_cual' },
  { label: 'pregunta_48,', value: 'pregunta_48' },
  { label: 'pregunta_48_cuales,', value: 'pregunta_48_cuales' },
  { label: 'pregunta_49,', value: 'pregunta_49' },
  { label: 'pregunta_49_cual,', value: 'pregunta_49_cual' },
  { label: 'pregunta_50,', value: 'pregunta_50' },
  { label: 'pregunta_50_cual,', value: 'pregunta_50_cual' },
  { label: 'pregunta_51,', value: 'pregunta_51' },
  { label: 'pregunta_51_cual,', value: 'pregunta_51_cual' },
  { label: 'pregunta_52,', value: 'pregunta_52' },
  { label: 'pregunta_52_cual,', value: 'pregunta_52_cual' },
  { label: 'pregunta_52_entidad,', value: 'pregunta_52_entidad' },
  { label: 'pregunta_53,', value: 'pregunta_53' },
  { label: 'pregunta_54,', value: 'pregunta_54' },
  { label: 'pregunta_55,', value: 'pregunta_55' },
  { label: 'pregunta_56,', value: 'pregunta_56' },
  { label: 'pregunta_57,', value: 'pregunta_57' },
  { label: 'pregunta_57_cuales,', value: 'pregunta_57_cuales' },
  { label: 'pregunta_58,', value: 'pregunta_58' },
  { label: 'pregunta_58_cuales,', value: 'pregunta_58_cuales' },
  { label: 'pregunta_59,', value: 'pregunta_59' },
  {
    label: 'pregunta_59_destino_transformadora_local,',
    value: 'pregunta_59_destino_transformadora_local',
  },
  {
    label: 'pregunta_59_destino_transformadora_nacional,',
    value: 'pregunta_59_destino_transformadora_nacional',
  },
  {
    label: 'pregunta_59_destino_venta_local,',
    value: 'pregunta_59_destino_venta_local',
  },
  {
    label: 'pregunta_59_destino_venta_nacional,',
    value: 'pregunta_59_destino_venta_nacional',
  },
  { label: 'pregunta_59_otros,', value: 'pregunta_59_otros' },
  { label: 'pregunta_60,', value: 'pregunta_60' },
  { label: 'pregunta_61,', value: 'pregunta_61' },
  { label: 'pregunta_61_cuales,', value: 'pregunta_61_cuales' },
  { label: 'pregunta_62,', value: 'pregunta_62' },
  { label: 'pregunta_63,', value: 'pregunta_63' },
  { label: 'pregunta_64,', value: 'pregunta_64' },
  { label: 'pregunta_64_porque,', value: 'pregunta_64_porque' },
  { label: 'pregunta_65,', value: 'pregunta_65' },
  { label: 'pregunta_65_porque,', value: 'pregunta_65_porque' },
  {
    label: 'pregunta_66_yogurt_presentacion,',
    value: 'pregunta_66_yogurt_presentacion',
  },
  { label: 'pregunta_66_yogurt_valor,', value: 'pregunta_66_yogurt_valor' },
  {
    label: 'pregunta_66_kumis_presentacion,',
    value: 'pregunta_66_kumis_presentacion',
  },
  { label: 'pregunta_66_kumis_valor,', value: 'pregunta_66_kumis_valor' },
  {
    label: 'pregunta_66_cuajada_presentacion,',
    value: 'pregunta_66_cuajada_presentacion',
  },
  { label: 'pregunta_66_cuajada_valor,', value: 'pregunta_66_cuajada_valor' },
  {
    label: 'pregunta_66_queso_doble_crema_presentacion,',
    value: 'pregunta_66_queso_doble_crema_presentacion',
  },
  {
    label: 'pregunta_66_queso_doble_crema_valor,',
    value: 'pregunta_66_queso_doble_crema_valor',
  },
  {
    label: 'pregunta_66_queso_campesino_presentacion,',
    value: 'pregunta_66_queso_campesino_presentacion',
  },
  {
    label: 'pregunta_66_queso_campesino_valor,',
    value: 'pregunta_66_queso_campesino_valor',
  },
  {
    label: 'pregunta_66_leche_presentacion,',
    value: 'pregunta_66_leche_presentacion',
  },
  { label: 'pregunta_66_leche_valor,', value: 'pregunta_66_leche_valor' },
  {
    label: 'pregunta_66_quesos_madurados_presentacion,',
    value: 'pregunta_66_quesos_madurados_presentacion',
  },
  {
    label: 'pregunta_66_quesos_madurados_valor,',
    value: 'pregunta_66_quesos_madurados_valor',
  },
  {
    label: 'pregunta_66_requeson_presentacion,',
    value: 'pregunta_66_requeson_presentacion',
  },
  {
    label: 'pregunta_66_requeson_valor,',
    value: 'pregunta_66_requeson_valor',
  },
  {
    label: 'pregunta_66_arequipe_presentacion,',
    value: 'pregunta_66_arequipe_presentacion',
  },
  {
    label: 'pregunta_66_arequipe_valor,',
    value: 'pregunta_66_arequipe_valor',
  },
  {
    label: 'pregunta_66_leche_pasteurizada_presentacion,',
    value: 'pregunta_66_leche_pasteurizada_presentacion',
  },
  {
    label: 'pregunta_66_leche_pasteurizada_valor,',
    value: 'pregunta_66_leche_pasteurizada_valor',
  },
  {
    label: 'pregunta_66_leche_UHT_presentacion,',
    value: 'pregunta_66_leche_UHT_presentacion',
  },
  {
    label: 'pregunta_66_leche_UHT_valor,',
    value: 'pregunta_66_leche_UHT_valor',
  },
  {
    label: 'pregunta_66_postres_presentacion,',
    value: 'pregunta_66_postres_presentacion',
  },
  { label: 'pregunta_66_postres_valor,', value: 'pregunta_66_postres_valor' },
  {
    label: 'pregunta_66_helados_presentacion,',
    value: 'pregunta_66_helados_presentacion',
  },
  { label: 'pregunta_66_helados_valor,', value: 'pregunta_66_helados_valor' },
  {
    label: 'pregunta_66_crema_de_leche_presentacion,',
    value: 'pregunta_66_crema_de_leche_presentacion',
  },
  {
    label: 'pregunta_66_crema_de_leche_valor,',
    value: 'pregunta_66_crema_de_leche_valor',
  },
  {
    label: 'pregunta_66_queso_mozzarella_presentacion,',
    value: 'pregunta_66_queso_mozzarella_presentacion',
  },
  {
    label: 'pregunta_66_queso_mozzarella_valor,',
    value: 'pregunta_66_queso_mozzarella_valor',
  },
  { label: 'pregunta_67,', value: 'pregunta_67' },
  { label: 'pregunta_67_distribucion,', value: 'pregunta_67_distribucion' },
  {
    label: 'pregunta_67_distribucion_quien,',
    value: 'pregunta_67_distribucion_quien',
  },
  { label: 'pregunta_68_energia,', value: 'pregunta_68_energia' },
  { label: 'pregunta_68_gas,', value: 'pregunta_68_gas' },
  { label: 'pregunta_68_agua,', value: 'pregunta_68_agua' },
  { label: 'pregunta_68_internet,', value: 'pregunta_68_internet' },
  { label: 'pregunta_68_telefonia,', value: 'pregunta_68_telefonia' },
  { label: 'pregunta_68_otro,', value: 'pregunta_68_otro' },
  { label: 'pregunta_68_otro_valor,', value: 'pregunta_68_otro_valor' },
  { label: 'observaciones', value: 'observaciones' },
  { label: 'fecha', value: 'fecha' },
  { label: 'nombre_encuestado', value: 'nombre_encuestado' },
  { label: 'cedula_encuestado', value: 'cedula_encuestado' },
  { label: 'nombre_encuestador', value: 'nombre_encuestador' },
  { label: 'cedula_encuestador', value: 'cedula_encuestador' },
];
